# Main entrypoint of the workflow.
configfile: "config/config.yaml"

print( config["collapse_locations"]["sd_focus"] )

rule all:
    input:
        pairs = "intermediates/pairs/pairs.txt",
        combined_results = "results/output/phylosor_results.csv",
        #hill_results = "results/output/hill_results.csv"

# Include support functions for pipeline
include: "rules/support.smk"

# Include phylosor rules for pipeline
include: "rules/phylosor.smk"

# Include jensen-shannon rules
include: "rules/jensenshannon.smk"
