input_locations:
  tree: "resources/global_rerooted.tree"
  metadata: "resources/gisaid_metadata.csv"
  chn_metadata: "resources/early_chn.csv"

columns:
  id_col: "accession_id"
  date_col: "date_collected"
  location_col: "site"

generate_nulls:
  groupby: "site"

prune_tree_to_pair:
  date_max: "2022-08-01"

pairs:
  min_sequences: 1000
  min_completeness: 0.75

compute_phylosor:
  window_size: 30

compute_js:
  resolution: "week"

