input_locations:
  tree: "resources/uncondensed-final-tree.nh"
  metadata: "resources/combined_md.csv"

columns:
  id_col: "accession_id"
  date_col: "date_collected"
  location_col: "site"

generate_nulls:
  groupby: "site"

prune_tree_to_pair:
  date_max: "2022-08-01"

compute_phylosor:
  window_size: 30

comput_js:
  resolution: "week"

